### ISSUE TITLE
[Bug] "Storage permission denied!" error even though there is no permission denied in android settings.

### ISSUE THREAD

**Issue by StaringLongingly** [HemantKArya/BloomeeTunes#10] opened 2024-05-13 13:47 UTC
self-explanatory

**Comment by HemantKArya** [comment] 2024-05-14 17:21
sure, I am looking into it, but it is hard to reproduce in my device can you provide some more information.

**Comment by punisher-303** [comment] 2024-07-20 03:47
> sure, I am looking into it, but it is hard to reproduce in my device can you provide some more information.

Android 13 & 14 doesn't show any storage permission they can't download any kind of music and always say's storage permission denied, and one more issues Android 12 and bellow can download but after changing that download patch we can't download any songs it says failed to download

**Comment by HemantKArya** [comment] 2024-07-21 10:17
Hi @punisher-303 I just merged your pull request to the main branch. I hope it will help lot of people to download song offline too. Thanx and I hope you will continue to contribute in future to this project.

As for now this issue can be closed.

**Closed by HemantKArya** 2024-07-21 10:17 UTC

**Comment by punisher-303** [comment] 2024-07-21 10:20
> Hi @punisher-303 I just merged your pull request to the main branch. I hope it will help lot of people to download song offline too. Thanx and I hope you will continue to contribute in future to this project.
> 
> As for now this issue can be closed.

I will give my all efforts for this project because I love this project and exiting ❤️
