### ISSUE TITLE
Saving playlists

### ISSUE THREAD

**Issue by GrandVizierNappa** [HemantKArya/BloomeeTunes#26] opened 2024-08-20 16:38 UTC
Everytime I import a playlist and close out of the app wait a day or so then it open it back up the playlists is not there and I have to reimport them in

**Comment by HemantKArya** [comment] 2024-08-21 04:40
it seems like your phone is deleting the files at midnight or at a particular time that resulting into deleting your personal app data, maybe it mistook your app data as cache files and deleted it, one solution may be try with switching off automatic cleanup and then see what happen. Or if doesn't help then for further information can you clarify that what android version and device you use it may help.

**Comment by GrandVizierNappa** [comment] 2024-08-21 05:15
I did download it from droidify app store with one of the f-droid repo I since deleted it and download it from the git hub source directly to see if it solves the problem. However I will give the other information if it also could point out any other known issues with the model that I'm using or if it's just me. Phone model is galaxy z flip5 running on android 14

**Comment by GrandVizierNappa** [comment] 2024-08-21 20:45
> it seems like your phone is deleting the files at midnight or at a particular time that resulting into deleting your personal app data, maybe it mistook your app data as cache files and deleted it, one solution may be try with switching off automatic cleanup from your smartphone storage setting and then see what happen. Or if doesn't help then for further information can you clarify that what android version and device you use it may help.

After redownloading from the GitHub page and waiting about a day or so the issue still seems to happen. When opening the app most things seem to take forever to load or don't load at all and will sit there in limbo for a long while even when swapping from Wi-Fi to cell data. Afterwards which i force close the app then reopen it does it load everything just fine and checking the library all playlists that was imported was removed. If this is a device problem or even my network blocking something it shouldn't please advise me as this is highly annoying to always have to readd my playlists.

**Comment by HemantKArya** [comment] 2024-08-22 02:44
Hi @GrandVizierNappa I know this is annoying for you, I am terribly sorry for that I still working on it. Btw did  you tried by switching off your auto cleanup provided by Samsung by default.

**Comment by GrandVizierNappa** [comment] 2024-08-22 15:40
@HemantKArya The Device Care feature doesn't seem to have an off or on toggle as it is a US model I cant just root and turn it off forcefully which it does kind of what you mention around late into the night is when it decides to clean up some cache and that file get removed. i haven't been able to repeat it outside of waiting till super late at night

**Comment by HemantKArya** [comment] 2024-08-22 16:32
Ahh I think I was bit wrong there because I used some Samsung device in my past and those had the feature for automatic storage booster/clear Unused files/optimization/etc I don't know it still exist or not but still this [ref. may work](https://r2.community.samsung.com/t5/Tech-Talk/How-to-turn-off-auto-delete-unnecessary-files/td-p/9470453#:~:text=Go%20to%20setting%2Cfind%20device,delete%20you%20app%20files%20automatically.) but still if you are saying that you don't have this configuration in settings then I guess we have to look for root cause for this problem that what is causing deleting the app data since the database is for playlist and other music metadata are stored in Document directory of App. So even if Samsung clears the cache, it shouldn't have affected the Document Dir/App Data as it is working fine in other devices I have tested (few Samsung device also).

**Comment by GrandVizierNappa** [comment] 2024-08-22 16:58
There is an auto optimization feature in the settings as it is always on can i cant turn it off also looking at the link and following the thread it seems that they either removed the setting to or just made default automatically as i am not able to see that auto delete unnecessary files. also if it helps i have manually deleted the cache of the app it self and ran the optimization manually outside of that if the phone is doing more then what i can do to try and replicate the issue then I'm unsure what else i can do

**Comment by HemantKArya** [comment] 2024-08-22 19:21
I think it will take time to reproduce this error in other device but in few days, I will try to download the Galaxy Zflip emulator and try to figure out with debug mode what's blocking/cleaning the Document data. Thanx for helping this much 🤗

**Comment by GrandVizierNappa** [comment] 2024-08-22 19:28
Welcome if you need anymore information or aid im willing to try and help

**Comment by HemantKArya** [comment] 2024-09-03 08:57
Hi @GrandVizierNappa can you now verify if this playlist persistence problem still exists or not?

**Comment by GrandVizierNappa** [comment] 2024-09-03 14:01
Yes i have verified that it is now working as intended i have gave it four or more days with out having to restore the backup. Thanks a bunch!!

**Comment by HemantKArya** [comment] 2024-09-03 19:30
yeah, please let me know after few days that is it working fine or not it will be helpful.

**Comment by GrandVizierNappa** [comment] 2024-09-04 17:12
@HemantKArya well after a few more days the playlists has persisted so the main issue has been resolved now the only thing I'm troubleshooting is why my phone is now not allowing me to have other apps have media controls which is the weirdest thing LOL.

**Comment by HemantKArya** [comment] 2024-09-04 17:34
Oh, nice to hear that now it is resolved, so if you think this issue is solved then please make sure to close this issue. About other issue do you mean controls in notification? or anywhere else. but still I would suggest you to if you can open a different issue since this is now solved and we track this issue in another specific issue thread.

**Comment by GrandVizierNappa** [comment] 2024-09-04 18:29
Idk how to describe it it seems like only Spotify can use the music player everything was fine till today i have no idea what changed didn't do anything different for it just stopped and its perplexing

**Closed** 2024-09-04 18:31 UTC
Labels: android

**Comment by HemantKArya** [comment] 2024-09-04 20:59
okay if it doesn't seem fine then feel free to create another issue for now this issue is now solved and marked as completed.🥰
thanx for helping this project.
